/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.State;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-10-22T07:26:37.397Z")

@Api(value = "FSM", description = "the FSM API")
public interface FSMApi {

    @ApiOperation(value = "Finite state machine simulation", nickname = "compute", notes = "A simulation of automatic traceability process. give in input a location (PI or PC or -) and the identification code of the test tube (from 0 to 4)", response = State.class, responseContainer = "List", tags={ "FSM", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = State.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Wrong location or ID") })
    @RequestMapping(value = "/FSM/{loc}/{id}",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<State>> compute(@ApiParam(value = "give in input PI or PC or -",required=true) @PathVariable("loc") String loc,@ApiParam(value = "Identification code from 0 to 4",required=true) @PathVariable("id") String id);

}
